source 'https://rubygems.org'

gem 'rails', '4.2.0.beta2'
gem 'responders'
gem 'sqlite3'
gem 'sass-rails', '5.0.0.beta1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'foreman'
gem 'guard-livereload'

gem 'garage', github: 'cookpad/garage'
gem 'kaminari'

group :development do
  gem 'spring'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.1.0'
  gem 'factory_girl_rails', '~> 4.4.1'
  gem 'pry-rails'
  gem 'debug_exceptions_json'
end
